actionCodes = {
	HeartBeat = 1,
	ClientDisconnect = 2,
	SysErrorMsg = 3,
	SysUpdateTime = 4,
	SysCommonNotice = 5,
	SysMaintainNotice = 6,

	RoleCreate = 100,
	RoleCreateResponse = 101,
	RoleAuthRequest = 102,
	RoleAuthResponse = 103,
	RoleQueryLogin = 104,
	RoleQueryResponse = 105,
	RoleKickDown = 106,
	RoleLoginRequest = 112,
	RoleLoginResponse = 113,
	RoleUpdateProperty = 114,
	RoleUpdatePveFormation = 115,
	RoleBornHeroRequest = 116,
	RoleBornHeroResponse = 117,
	RoleBuyItemBySoulRequest = 118,
	RoleBuyItemBySoulResponse = 119,
	RoleRefreshLegendShopRequest = 120,
	RoleRefreshLegendShopResponse = 121,
	RoleDigestInfoRequest = 122,
	RoleDigestInfoResponse = 123,
	RoleReConnect = 124,
	RoleSignRequest = 125,
	RoleRefreshPvpShopRequest = 126,
	RoleRefreshPvpShopResponse = 127,
	RoleBuyItemByZhangongRequest = 128,
	RoleBuyItemByZhangongResponse = 129,
	RoleGetLevelGiftRequest = 130,
	RoleGetLevelGiftResponse = 131,
	RoleRecvTaskAwardRequest = 132,
	RoleRecvTaskAwardResponse = 133,
	RoleGetServerGiftRequest = 134,
	RoleGetServerGiftResponse = 135,
	RoleBuyItemAndUseRequest = 136,
	RoleBuyItemAndUseResponse = 137,
	RoleBuyMoneyRequest = 138,
	RoleCanEatChickenRequest = 139,
	RoleEatChickenRequest = 140,
	RoleNotifyNewEvents = 141,
	RoleRequestNewEvents = 142,
	RoleUpdateDailyProps = 143,
	RoleReHealthTimeRequest = 149,
	RoleRenameRequest = 150,
	RoleBuyHeroBagRequest = 151,
	RoleBuyHeroBagResponse = 152,
	RoleUpdateProperties = 153,

	RoleLoadHeroReq = 154,
	RoleLoadHeroPost = 155,

	RoleRankRequest = 156,
	RoleRankResponse = 157,

	RoleShopRequest = 158,
	RoleShopResponse = 159,
	RoleShopBuyRequest = 160,
	RoleShopBuyResponse = 161,
	RoleShopRefresRequest = 162,
	RoleShopRefresResponse = 163,

	RoleRandomNameRequest = 164,
	RoleRandomNameResponse = 165,

	RoleActiveSuccess = 166,
	RoleSignResponse = 167,
	RoleExchangeRequest = 168,
	RoleExchangeResponse = 169,

	RoleGetAccumulatedRechargeGiftRequest = 170,
	RoleGetAccumulatedRechargeGiftResponse = 171,
	RoleGetActivityTimeListRequest = 172,
	RoleGetActivityTimeListRespose = 173,

	RoleGetFundRequest = 174,
	RoleComposeBattleSoul = 175,
	RoleWorldNotice = 176,

	CarbonLoadDataSet = 201,
	CarbonStartGameRequest = 202,
	CarbonStartGameResponse = 203,
	CarbonEndGameRequest = 204,
	CarbonEndGameResponse = 205,
	CarbonActDataRequest = 206,
	CarbonActDataResponse = 207,
	CarbonAssistChooseRequest = 210,
	CarbonAssistChooseResponse = 211,
	CarbonKillBossRequest = 212,
	CarbonKillBossResponse = 213,
	CarbonResetRequest = 214,
	CarbonResetResponse = 215,
	CarbonSweepRequest = 216,
	CarbonSweepResponse = 217,
	CarbonOpenAwardRequest = 218,
	CarbonOpenAwardResponse = 219,

	MoneyBattleRequest = 231,
	MoneyBattleEndRequest = 232,
	MoneyBattleEnterRequest = 233,
	ExpBattleEnterRequest = 234,
	ExpBattleRequest = 235,
	ExpBattleEndRequest = 236,
	TrialBattleRequest = 237,
	TrialBattleEndRequest = 238,

	TowerDataRequest = 251,
	TowerDataResponse = 252,
	TowerDataSave = 253,
	TowerBattleBegin = 254,
	TowerBattleEnd = 255,
	TowerRankRequest = 256,
	TowerRankResponse = 257,
	TowerAwardGotRequest = 258,
	TowerAwardGotResponse = 259,
	TowerAttrModifyRequest = 250,
	TowerAttrModifyResponse = 261,
	TowerOpenAwardRequest = 262,
	TowerOpenAwardResponse = 263,

	LegendBattleBegin = 280,
	LegendBattleEndRequest = 281,
	LegendBattleEndResponse = 282,
	LegendRefreshRequest = 283,
	LegendRefreshResponse = 284,
	LegendBattleEnterRequest = 285,
	LegendBattleEnterResponse = 286,
	LegendBattleAddCount = 287,

	HeroLoadDataSet = 301,
	HeroUpdateProperty = 302,
	HeroIntensify = 303,
	HeroEvolution = 304,
	HeroChoose = 305,
	HeroSellRequest = 306,
	HeroSellResponse = 307,
	HeroEvolutionResponse = 308,
	HeroIntensifyResponse = 309,
	HeroAssistantChangeRequest = 310,
	HeroAssistantChangeResponse = 311,
	HeroAssistantCancelRequest = 312,
	HeroAssistantCancelResponse = 313,
	HeroAllRequest = 314,
	HeroAllResponse = 315,
	HeroChooseResponse = 316,
	HeroSkillLevelUpRequest = 317,
	HeroSkillLevelUpResponse = 318,
	HeroWakeLevelUpRequest = 319,
	HeroWakeLevelUpResponse = 320,
	HeroDecomposeRequest = 321,
	HeroDecomposeResponse = 322,
	HeroStarUpRequest = 323,
	HeroPartnerRequest = 324,
	HeroBattleSoulRequest = 325,

	PvpSearchMatchRequest = 400,
	PvpSearchMatchResponse =401,
	PvpChooseOpponent = 402,
	PvpFormationInfo = 403,
	PvpEndGameNotify = 405,
	PvpBuyCount = 406,
	PvpEraceCdTime = 407,
	PvpRankRequest = 408,
	PvpRankResponse = 409,
	PvpGiftAwardRequest = 410,
	PvpEndGameResponse = 411,
	PvpBattleReportRequest = 412,
	PvpBattleReportResponse = 413,
	PvpBattleEnterRequest = 414,
	PvpBattleEnterResponse = 415,

	FriendSearchByName = 430,
	FriendRandomSearch = 431,
	FriendMatchedRoleResponse = 432,
	FriendListFriendRequest = 433,
	FriendListFriendResponse = 434,
	FriendCreateApplication = 435,
	FriendApplicationsRequest = 436,
	FriendApplicationsResponse = 437,
	FriendHandleApplication = 438,
	FriendDonateHealth = 439,
	FriendReceiveHealth = 440,
	FriendDelete = 441,

	GiftListRequest = 460,
	GiftListResponse = 461,
	GiftReceiveRequest = 462,
	GiftReceiveResponse = 463,
	GiftRechargeAwardRequest = 464,
	GiftRechargeAwardResponse = 465,

	StoreRechargeRequest = 470,
	StoreRechargeResponse = 471,
	StoreDrawCardRequest = 472,
	StoreDrawCardResponse = 473,
	StoreBuyItemRequest = 474,
	StoreBuyItemResponse = 475,
	StoreListItemRequest = 476,
	StoreListItemResponse = 477,
	StoreRechargeResult = 478,
	StorePlatformNotice = 479,

	StoreGetShopThrosholdRequest = 480,
	StoreGetShopThrosholdResponse = 481,

	BeautyNormalTrainRequest = 501,
	BeautyNormalTrainResponse = 502,
	BeautyHighTrainRequest = 503,
	BeautyHighTrainResponse = 504,
	BeautyNormalPotentialRequest = 505,
	BeautyNormalPotentialResponse = 506,
	BeautyHighPotentialRequest = 507,
	BeautyHighPotentialResponse = 508,
	BeautyPotentialSaveRequest = 509,
	BeautyPotentialSaveResponse = 510,
	BeautyEvolutionRequest = 511,
	BeautyEvolutionResponse = 512,
	BeautyEmployRequest = 513,
	BeautyEmployResponse = 514,
	BeautyFightRequest = 515,
	BeautyFightResponse = 516,
	BeautyRestRequest = 517,
	BeautyRestResponse = 518,

	EmailListRequest = 531,
	EmailListResponse = 532,
	EmailCheckRequest = 533,
	EmailCheckResponse = 534,
	EmailRecvAttachmentRequest = 535,
	EmailRecvAttachmentResponse = 536,

	ItemUpdateProperty = 541,
	ItemUseRequest = 542,
	ItemUseResponse = 543,
	ItemSellRequest = 544,
	ItemSellResponse = 545,

	FragmentDecomposeRequest = 561,
	FragmentDecomposeResponse = 562,
	FragmentExchangeRequest = 563,
	FragmentExchangeResponse = 564,
	FragmentLoadDataSet = 565,

	TechWashPointRequest = 571,
	TechWashPointResponse = 572,
	TechPhasePromoteRequest = 573,
	TechPhasePromoteResponse = 574,
	TechLeveupRequest = 575,
	TechLeveupResponse = 576,

	StarHeroPromoteRequest = 581,
	StarHeroPromoteResponse = 582,	

	ChatSendRequest = 591,
	ChatReceiveResponse = 592,

	GmSendRequest = 601,
	GmReceiveResponse = 602,

	EquipIntensifyRequest = 610,
	EquipIntensifyResponse = 611,
	EquipChooseRequest = 612,
	EquipChooseResponse = 613,
	EquipSellRequest = 614,
	EquipSellResponse = 615,
	EquipLoadDataSet = 616,
	EquipFragmentLoadDataSet = 617,
	EquipFragmentComposeRequest = 618,
	EquipFragmentComposeResponse = 619,
	EquipEvolRequest = 620,
	EquipUpdateProperty = 621,

	ExpeditionRequest = 630,
	ExpeditionResponse = 631,
	EnterExpeditionRequest = 632,
	EnterExpeditionResponse = 634,
	EndExpeditionRequest = 635,
	EndExpeditionReponse = 636,
	DrawExpedition = 637,
	DrawExpeditionResponse = 638,
	ExpeditionJoinRequest = 639,
	ExpeditionJoinResponse = 640,
	ExpeditionRestartReq = 641,
	ExpeditionRestartRes = 642,
	UpdateYzFormationReq = 643,
	UpdateYzFormationRes = 644,
}

actionModules = {
	[actionCodes.ClientDisconnect] = "System.disconnectRole",
	[actionCodes.SysErrorMsg] = "System.handleErrorMsg",
	[actionCodes.SysUpdateTime] = "System.updateTime",
	[actionCodes.SysCommonNotice] = "System.commonNotice",
	[actionCodes.SysMaintainNotice] = "System.maintainNotice",

	[actionCodes.FragmentDecomposeRequest] = "Role.decomposeFragmentRequest",
	[actionCodes.FragmentDecomposeResponse] = "Role.decomposeFragmentResponse",
	[actionCodes.FragmentExchangeRequest] = "Role.fragmentExchangeRequest",
	[actionCodes.FragmentExchangeResponse] = "Role.fragmentExchangeResponse",
	[actionCodes.FragmentLoadDataSet] = "Role.loadFragments",

	[actionCodes.TechWashPointRequest] = "Role.washTechPointReqeust",
	[actionCodes.TechWashPointResponse] = "Role.washTechPointResponse",
	[actionCodes.TechPhasePromoteRequest] = "Role.promoteTechPhaseRequest",
	[actionCodes.TechPhasePromoteResponse] = "Role.promoteTechPhaseResponse",
	[actionCodes.TechLeveupRequest] = "Role.techLevelupRequest",
	[actionCodes.TechLeveupResponse] = "Role.techLevelupResponse",

	[actionCodes.StarHeroPromoteRequest] = "Role.promoteStarHeroRequest",
	[actionCodes.StarHeroPromoteResponse] = "Role.promoteStarHeroResponse",

	[actionCodes.CarbonLoadDataSet] = "Carbon.loadDataSet",
	[actionCodes.CarbonStartGameRequest] = "Carbon.startGameRequest",
	[actionCodes.CarbonStartGameResponse] = "Carbon.startGameResponse",
	[actionCodes.CarbonEndGameRequest] = "Carbon.endGameRequest",
	[actionCodes.CarbonEndGameResponse] = "Carbon.endGameResponse",
	[actionCodes.CarbonActDataRequest] = "Carbon.actDataRequest",
	[actionCodes.CarbonActDataResponse] = "Carbon.actDataResponse",
	[actionCodes.CarbonAssistChooseRequest] = "Carbon.chooseAssist",
	[actionCodes.CarbonAssistChooseResponse] = "Carbon.chooseAssistResponse",
	[actionCodes.CarbonOpenAwardRequest] = "Carbon.openMapAwardRequest",
	[actionCodes.CarbonOpenAwardResponse] = "Carbon.openMapAwardResponse",
	[actionCodes.CarbonKillBossRequest] = "Carbon.killBossRequest",
	[actionCodes.CarbonKillBossResponse] = "Carbon.killBossResponse",
	[actionCodes.CarbonResetRequest] = "Carbon.carbonResetRequest",
	[actionCodes.CarbonResetResponse] = "Carbon.carbonResetResponse",

	[actionCodes.MoneyBattleRequest] = "Carbon.moneyBattleRequest",
	[actionCodes.MoneyBattleEndRequest] = "Carbon.moneyBattleEndRequest",
	[actionCodes.MoneyBattleEnterRequest] = "Carbon.moneyBattleEnterRequest",
	[actionCodes.ExpBattleEnterRequest] = "Carbon.expBattleEnterRequest",
	[actionCodes.ExpBattleRequest] = "Carbon.expBattleRequest",
	[actionCodes.ExpBattleEndRequest] = "Carbon.expBattleEndRequest",
	[actionCodes.TrialBattleRequest] = "Carbon.trialBattleRequest",
	[actionCodes.TrialBattleEndRequest] = "Carbon.trialBattleEndRequest",	

	[actionCodes.TowerDataRequest] = "Carbon.towerDataRequest",
	[actionCodes.TowerDataResponse] = "Carbon.towerDataResponse",
	[actionCodes.TowerDataSave] = "Carbon.updateTowerData",
	[actionCodes.TowerBattleBegin] = "Carbon.towerBattleBegin",
	[actionCodes.TowerBattleEnd] = "Carbon.towerBattleEnd",
	[actionCodes.TowerRankRequest] = "Carbon.towerRankRequest",
	[actionCodes.TowerRankResponse] = "Carbon.towerRankResponse",
	[actionCodes.TowerAwardGotRequest] = "Carbon.towerAwardGotRequest",
	[actionCodes.TowerAwardGotResponse] = "Carbon.towerAwardGotResponse",
	[actionCodes.TowerAttrModifyRequest] = "Carbon.towerAttrModifyRequest",
	[actionCodes.TowerAttrModifyResponse] = "Carbon.towerAttrModifyResponse",
	[actionCodes.TowerOpenAwardRequest] = "Carbon.towerOpenAwardRequest",
	[actionCodes.TowerOpenAwardResponse] = "Carbon.towerOpenAwardResponse",
	

	[actionCodes.LegendBattleEnterRequest] = "Carbon.legendEnterRequest",
	[actionCodes.LegendBattleEnterResponse] = "Carbon.legendEnterResponse",
	[actionCodes.LegendBattleEndRequest] = "Carbon.legendEndGameRequest",
	[actionCodes.LegendBattleEndResponse] = "Carbon.legendEndGameResponse",
	[actionCodes.LegendRefreshRequest] = "Carbon.refreshLegendCarbon",
	[actionCodes.LegendRefreshResponse] = "Carbon.refreshLegendResponse",
	[actionCodes.LegendBattleAddCount] = "Carbon.addLegendBattleCnt",

	[actionCodes.HeroLoadDataSet] = "Hero.loadDataSet",
	[actionCodes.HeroUpdateProperty] = "Hero.updateProperty",
	[actionCodes.HeroIntensify] = "Hero.intensify",
	[actionCodes.HeroEvolution] = "Hero.evolution",
	[actionCodes.HeroChoose] = "Hero.choose",
	[actionCodes.HeroSellRequest] = "Hero.sellHeros",
	[actionCodes.HeroSellResponse] = "Hero.sellHeroResponse",
	[actionCodes.HeroEvolutionResponse] = "Hero.evolutionResponse",
	[actionCodes.HeroIntensifyResponse] = "Hero.intensifyResponse",
	[actionCodes.HeroAssistantChangeRequest] = "Hero.changeAssistantRequest",
	[actionCodes.HeroAssistantChangeResponse] = "Hero.changeAssistantResponse",
	[actionCodes.HeroAssistantCancelRequest] = "Hero.cancelAssistantRequest",
	[actionCodes.HeroAssistantCancelResponse] = "Hero.cancelAssistantResponse",
	[actionCodes.HeroAllRequest] = "Hero.allRequest",
	[actionCodes.HeroAllResponse] = "Hero.allResponse",
	[actionCodes.HeroChooseResponse] = "Hero.chooseResponse",
	[actionCodes.HeroSkillLevelUpRequest] = "Hero.skillLevelUpRequest",
	[actionCodes.HeroSkillLevelUpResponse] = "Hero.skillLevelUpResponse",
	[actionCodes.HeroWakeLevelUpRequest] = "Hero.heroWakeLevelUpRequest",
	[actionCodes.HeroWakeLevelUpResponse] = "Hero.heroWakeLevelUpResponse",
	[actionCodes.HeroDecomposeRequest] = "Hero.heroDecomposeRequest",
	[actionCodes.HeroDecomposeResponse] = "Hero.heroDecomposeResponse",
	[actionCodes.HeroStarUpRequest] = "Hero.heroStarUpRequest",
	[actionCodes.HeroPartnerRequest] = "Hero.heroPartnerRequest",
	[actionCodes.HeroBattleSoulRequest] = "Hero.inlayBattleSoul",

	[actionCodes.PvpSearchMatchRequest] = "Pvp.searchMatchRoles",
	[actionCodes.PvpSearchMatchResponse] = "Pvp.matchRolesResponse",
	[actionCodes.PvpChooseOpponent] = "Pvp.chooseOpponent",
	[actionCodes.PvpFormationInfo] = "Pvp.formationInfoResponse",
	[actionCodes.PvpEndGameNotify] = "Pvp.endGameNotify",
	[actionCodes.PvpBuyCount] = "Pvp.buyPvpCount",
	[actionCodes.PvpEraceCdTime] = "Pvp.eraseCdTime",
	[actionCodes.PvpRankRequest] = "Pvp.queryRankList",
	[actionCodes.PvpRankResponse] = "Pvp.rankListResponse",
	[actionCodes.PvpGiftAwardRequest] = "Pvp.giftAwardRequest",
	[actionCodes.PvpEndGameResponse] = "Pvp.endGameResponse",
	[actionCodes.PvpBattleReportRequest] = "Pvp.battleReportRequest",
	[actionCodes.PvpBattleReportResponse] = "Pvp.battleReportResponse",
	[actionCodes.PvpBattleEnterRequest] = "Pvp.battleEnterRequest",
	[actionCodes.PvpBattleEnterResponse] = "Pvp.battleEnterResponse",

	[actionCodes.FriendSearchByName] = "Friend.searchRoleByName",
	[actionCodes.FriendRandomSearch] = "Friend.randomSearchRole",
	[actionCodes.FriendMatchedRoleResponse] = "Friend.matchNameRoleResponse",
	[actionCodes.FriendListFriendRequest] = "Friend.listFriendRequest",
	[actionCodes.FriendListFriendResponse] = "Friend.friendListResponse",
	[actionCodes.FriendCreateApplication] = "Friend.createApplication",
	[actionCodes.FriendApplicationsRequest] = "Friend.listApplications",
	[actionCodes.FriendApplicationsResponse] = "Friend.applicationListResponse",
	[actionCodes.FriendHandleApplication] = "Friend.handleApplication",
	[actionCodes.FriendDonateHealth] = "Friend.donateHealth",
	[actionCodes.FriendReceiveHealth] = "Friend.receiveHealth",
	[actionCodes.FriendDelete]	= "Friend.deleteFriend",

	[actionCodes.GiftListRequest] = "Gift.listGiftRequest",
	[actionCodes.GiftListResponse] = "Gift.listGiftResponse",
	[actionCodes.GiftReceiveRequest] = "Gift.receiveRequest",
	[actionCodes.GiftReceiveResponse] = "Gift.receiveResponse",
	[actionCodes.GiftRechargeAwardRequest] = "Gift.RechargeAwardRequest",
	[actionCodes.GiftRechargeAwardResponse] = "Gift.RechargeAwardResponse",

	[actionCodes.StoreRechargeRequest] = "Store.rechargeRequest",
	[actionCodes.StoreRechargeResponse] = "Store.rechargeResponse",
	[actionCodes.StoreDrawCardRequest] = "Store.buyCardPackage",
	[actionCodes.StoreDrawCardResponse] = "Store.drawCardResponse",
	[actionCodes.StoreBuyItemRequest] = "Store.buyItemRequest",
	[actionCodes.StoreBuyItemResponse] = "Store.buyItemResponse",
	[actionCodes.StoreListItemRequest] = "Store.listItemsRequest",
	[actionCodes.StoreListItemResponse] = "Store.listItemsResponse",
	[actionCodes.StoreRechargeResult] = "Store.rechargeResult",
	[actionCodes.StorePlatformNotice] = "Store.platformNotice",
	[actionCodes.StoreGetShopThrosholdRequest] = "Store.getShopThrosholdRequest",
	[actionCodes.StoreGetShopThrosholdResponse] = "Store.getShopThrosholdResponse",

	[actionCodes.BeautyNormalTrainRequest] = "Beauty.normalTrainRequest",
	[actionCodes.BeautyNormalTrainResponse] = "Beauty.normalTrainResponse",
	[actionCodes.BeautyHighTrainRequest] = "Beauty.highTrainRequest",
	[actionCodes.BeautyHighTrainResponse] = "Beauty.highTrainResponse",
	[actionCodes.BeautyNormalPotentialRequest] = "Beauty.normalPotentialRequest",
	[actionCodes.BeautyNormalPotentialResponse] = "Beauty.normalPotentialResponse",
	[actionCodes.BeautyHighPotentialRequest] = "Beauty.highPotentialRequest",
	[actionCodes.BeautyHighPotentialResponse] = "Beauty.highPotentialResponse",
	[actionCodes.BeautyPotentialSaveRequest] = "Beauty.potentialSaveRequest",
	[actionCodes.BeautyPotentialSaveResponse] = "Beauty.potentialSaveResponse",
	[actionCodes.BeautyEvolutionRequest] = "Beauty.evolutionRequest",
	[actionCodes.BeautyEvolutionResponse] = "Beauty.evolutionResponse",
	[actionCodes.BeautyEmployRequest] = "Beauty.employRequest",
	[actionCodes.BeautyEmployResponse] = "Beauty.employResponse",
	[actionCodes.BeautyFightRequest] = "Beauty.fightRequest",
	[actionCodes.BeautyFightResponse] = "Beauty.fightResponse",
	[actionCodes.BeautyRestRequest] = "Beauty.restRequest",
	[actionCodes.BeautyRestResponse] = "Beauty.restResponse",

	[actionCodes.CarbonSweepRequest] = "Carbon.sweepRequest",
	[actionCodes.CarbonSweepResponse] = "Carbon.sweepResponse",

	[actionCodes.EmailListRequest] = "Email.listRequest",
	[actionCodes.EmailListResponse] = "Email.listResponse",
	[actionCodes.EmailCheckRequest] = "Email.checkRequest",
	[actionCodes.EmailCheckResponse] = "Email.checkResponse",
	[actionCodes.EmailRecvAttachmentRequest] = "Email.recvAttachmentRequest",
	[actionCodes.EmailRecvAttachmentResponse] = "Email.recvAttachmentReponse",

	[actionCodes.ChatSendRequest] = "Role.chatSendRequest",
	[actionCodes.ChatReceiveResponse] = "Role.chatReceiveResponse",

	[actionCodes.GmSendRequest] = "Gm.GmRequest",
	[actionCodes.GmReceiveResponse] = "Gm.GmResponse",

	[actionCodes.ItemUpdateProperty] = "Role.updateItemProperty",
	[actionCodes.ItemUseRequest] = "Role.itemUseRequest",
	[actionCodes.ItemUseResponse] = "Role.itemUseResponse",
	[actionCodes.ItemSellRequest] = "Role.itemSellRequest",
	[actionCodes.ItemSellResponse] = "Role.itemSellResponse",

	[actionCodes.RoleCreate] = "Role.create",
	[actionCodes.RoleCreateResponse] = "Role.createResponse",
	[actionCodes.RoleAuthResponse] = "Role.authResponse",
	[actionCodes.RoleLoginRequest] = "Role.login",
	[actionCodes.RoleQueryLogin] = "Role.queryLogin",
	[actionCodes.RoleQueryResponse] = "Role.queryResponse",
	[actionCodes.RoleLoginResponse] = "Role.loginResponse",
	[actionCodes.RoleKickDown] = "Role.kickDown",
	[actionCodes.RoleUpdateProperty] = "Role.updateProperty",
	[actionCodes.RoleUpdatePveFormation] = "Role.updatePveFormation",
	[actionCodes.RoleBornHeroRequest] = "Role.bornHeroRequest",
	[actionCodes.RoleBornHeroResponse] = "Role.bornHeroResponse",
	[actionCodes.RoleBuyItemBySoulRequest] = "Role.buyItemBySoulRequest",
	[actionCodes.RoleBuyItemBySoulResponse] = "Role.buyItemBySoulResponse",
	[actionCodes.RoleDigestInfoRequest] = "Role.digestInfoRequest",
	[actionCodes.RoleDigestInfoResponse] = "Role.digestInfoResponse",
	[actionCodes.RoleReConnect] = "Role.reConnect",
	[actionCodes.RoleSignRequest] = "Role.signRequest",
	[actionCodes.RoleRefreshPvpShopRequest] = "Role.refreshPvpShopRequest",
	[actionCodes.RoleRefreshPvpShopResponse] = "Role.refreshPvpShopResponse",
	[actionCodes.RoleBuyItemByZhangongRequest] = "Role.buyItemByZhangongRequest",
	[actionCodes.RoleBuyItemByZhangongResponse] = "Role.buyItemByZhangongResponse",
	[actionCodes.RoleGetLevelGiftRequest] = "Role.getLevelGiftRequest",
	[actionCodes.RoleGetLevelGiftResponse] = "Role.getLevelGiftResponse",
	[actionCodes.RoleRecvTaskAwardRequest] = "Role.recvTaskAwardRequest",
	[actionCodes.RoleRecvTaskAwardResponse] = "Role.recvTaskAwardResponse",
	[actionCodes.RoleGetServerGiftRequest] = "Role.getServerGiftRequest",
	[actionCodes.RoleGetServerGiftResponse] = "Role.getServerGiftResponse",
	[actionCodes.RoleGetAccumulatedRechargeGiftRequest] = "Role.getAccumulatedRechargeGiftRequest",
	[actionCodes.RoleGetAccumulatedRechargeGiftResponse] = "Role.getAccumulatedRechargeGiftResponse",
	[actionCodes.RoleGetActivityTimeListRequest] = "Role.getActivityTimeListRequest",
	[actionCodes.RoleGetActivityTimeListRespose] = "Role.getActivityTimeListRespose",
	[actionCodes.RoleBuyItemAndUseRequest] = "Role.buyItemAndUseRequest",
	[actionCodes.RoleBuyItemAndUseResponse] = "Role.buyItemAndUseResponse",
	[actionCodes.RoleBuyMoneyRequest] = "Role.buyMoneyRequest",
	[actionCodes.RoleCanEatChickenRequest] = "Role.canEatChickenRequest",
	[actionCodes.RoleEatChickenRequest] = "Role.eatChickenRequest",
	[actionCodes.RoleNotifyNewEvents] = "Role.notifyNewEvents",
	[actionCodes.RoleRequestNewEvents] = "Role.requestNewEvents",
	[actionCodes.RoleUpdateDailyProps] = "Role.requestDailyProps",
	[actionCodes.RoleReHealthTimeRequest] = "Role.reHealthTimeRequest",
	[actionCodes.RoleRenameRequest] = "Role.renameRequest",
	[actionCodes.RoleBuyHeroBagRequest] = "Role.buyHeroBagRequest",
	[actionCodes.RoleBuyHeroBagResponse] = "Role.buyHeroBagResponse",
	[actionCodes.RoleUpdateProperties] = "Role.UpdateProperties",

	[actionCodes.RoleLoadHeroReq] = "Role.loadHeroReq",
	[actionCodes.RoleLoadHeroPost] = "Role.loadHeroPost",

	[actionCodes.RoleRankRequest] = "Role.rankRequest",
	[actionCodes.RoleRankResponse] = "Role.rankResponse",
	
	[actionCodes.RoleShopRequest] = "Role.shopRequest",
	[actionCodes.RoleShopResponse] = "Role.shopResponse",
	[actionCodes.RoleShopBuyRequest] = "Role.shopBuyRequest",
	[actionCodes.RoleShopBuyResponse] = "Role.shopBuyResponse",
	[actionCodes.RoleShopRefresRequest] = "Role.shopRefreshRequest",
	[actionCodes.RoleShopRefresResponse] = "Role.shopRefreshResponse",

	[actionCodes.RoleRandomNameRequest] = "Role.randomNameRequest",
	[actionCodes.RoleRandomNameResponse] = "Role.randomNameResponse",

	[actionCodes.RoleActiveSuccess] = "Role.activeSuccess",
	[actionCodes.RoleSignResponse] = "Role.signResponse",
	[actionCodes.RoleExchangeRequest] = "Role.exchange",
	[actionCodes.RoleExchangeResponse] = "Role.excangeResponse",
	[actionCodes.RoleGetFundRequest] = "Role.fund",
	[actionCodes.RoleComposeBattleSoul] = "Role.composeBattleSoul",
	[actionCodes.RoleWorldNotice] = "Role.roleWorldNotice",

	[actionCodes.EquipIntensifyRequest] = "Equip.intensify",
	[actionCodes.EquipIntensifyResponse] = "Equip.intensifyResponse",
	[actionCodes.EquipChooseRequest] = "Equip.choose",
	[actionCodes.EquipChooseResponse] = "Equip.chooseResponse",
	[actionCodes.EquipSellRequest] = "Equip.sell",
	[actionCodes.EquipSellResponse] = "Equip.sellResponse",
	[actionCodes.EquipLoadDataSet] = "Equip.loadDataSet",
	[actionCodes.EquipFragmentLoadDataSet] = "Equip.fragmentLoadDataSet",
	[actionCodes.EquipFragmentComposeRequest] = "Equip.fragmentCompose",
	[actionCodes.EquipFragmentComposeResponse] = "Equip.fragmentComposeResponse",
	[actionCodes.EquipEvolRequest] = "Equip.evolution",
	[actionCodes.EquipUpdateProperty] = "Equip.updateProperty",

	[actionCodes.ExpeditionRequest] = "Expedition.expeditionReq",
	[actionCodes.ExpeditionResponse] = "Expedition.expeditionRes",
	[actionCodes.EnterExpeditionRequest] = "Expedition.enterExpeditionReq",
	[actionCodes.EnterExpeditionResponse] = "Expedition.enterExpeditionRes",
	[actionCodes.EndExpeditionRequest] = "Expedition.endExpeditionReq",
	[actionCodes.EndExpeditionReponse] = "Expedition.endExpeditionRes",
	[actionCodes.DrawExpedition] = "Expedition.drawAward",
	[actionCodes.DrawExpeditionResponse] = "Expedition.drawAwardRes",
	[actionCodes.ExpeditionJoinRequest] = "Expedition.joinReq",
	[actionCodes.ExpeditionJoinResponse] = "Expedition.joinRes",
	[actionCodes.ExpeditionRestartReq] = "Expedition.restartExpedition",
	[actionCodes.ExpeditionRestartRes] = "Expedition.restartResponse",

	[actionCodes.UpdateYzFormationReq] = "Expedition.updateFormationReq",
	[actionCodes.UpdateYzFormationRes] = "Expedition.updateFormationRes",
}