SYS_ERR_UNKNOWN = 1 			-- 未知错误
SYS_ERR_CLIENT_OPERATION = 2            -- 客户端非法操作

SYS_ERR_CARBON_NOT_EXIST = 20			-- 副本不存在
SYS_ERR_CARBON_PLAY_COUNT_LIMIT = 21	-- 当天副本次数上限
SYS_ERR_TOWER_PLAY_COUNT_LIMIT = 22 	-- 刷塔次数上限
SYS_ERR_LEGEND_BATTLE_BUY_LIMIT = 23 	-- 名将挑战次数购买上限
SYS_ERR_LEGEND_BATTLE_LIMIT = 24 		-- 名将挑战次数不足
SYS_ERR_HELL_BATTLE_LIMIT = 25 			-- 地狱挑战次数不够
SYS_ERR_PVP_BATTLE_COUNT_LIMIT = 26 	-- PVP挑战次数不够

SYS_ERR_YUANBAO_NOT_ENOUGH = 50 -- 元宝不足
SYS_ERR_MONEY_NOT_ENOUGH = 51	-- 金币不足
SYS_ERR_HEALTH_NOT_ENOUGH = 52	-- 体力值不足
SYS_ERR_HEALTH_FULL = 53		-- 体力值已满
SYS_ERR_YANZHI_NOT_ENOUGH = 54	-- 胭脂不足
SYS_ERR_LINGPAI_NOT_ENOUGH = 55	-- 令牌不够
SYS_ERR_FRIEND_VALUE_NOT_ENOUGH = 56 --友情值不够
SYS_ERR_FINAL_HEALTH_FULL = 57 --已达体力值最终上限
SYS_ERR_ITEM_NUM_NOT_ENOUGH = 58

SYS_ERR_FRIEND_COUNT_LIMIT = 70	-- 好友人数达到上限
SYS_ERR_FRIEND_APPLICATION_AGREE = 71	-- 同意其他人的申请
SYS_ERR_FRIEND_APPLICATION_DENY = 72	-- 拒绝其他人的申请
SYS_ERR_FRIEND_DELETE_SUCCESS = 73		-- 删除好友成功
SYS_ERR_FRIEND_DONATE_HEALTH_LIMIT = 74	-- 赠送体力次数上限
SYS_ERR_FRIEND_HAS_DONATED = 75			-- 已经赠送过该好友
SYS_ERR_FRIEND_DONATE_SUCCESS = 76		-- 赠送好友体力成功
SYS_ERR_FRIEND_RECV_LIMIT = 77			-- 体力领取上限
SYS_ERR_FRIEND_RECV_SUCCESS = 78		-- 体力领取成功

SYS_ERR_PVP_BUY_COUNT_LIMIT = 100	-- 当前玩家购买pvp次数已经超限
SYS_ERR_PVP_OPPONENT_LEVEL_CHANGE = 103	-- 被挑战者等级已经被改变
SYS_ERR_PVP_LOW_ROLE_LEVEL = 104	-- 当前玩家等级不够
SYS_ERR_PVP_TODAY_RUN_OUT = 105	-- 当天的pvp次数已经用完	
SYS_ERR_PVP_IN_CD_TIME = 106		-- 还在pvp的cd时间内
SYS_ERR_PVP_OPPONENT_BE_CHOSEN = 107	-- 当前玩家已经被挑战着

SYS_ERR_CHOOSE_SAME_TYPE_HERO = 110	-- 上阵同类型武将
SYS_ERR_HERO_BAG_LIMIT = 111        -- 武将背包已满

SYS_ERR_HERO_MAIN_LEVEL_LIMIT = 120	-- 强化主将等级已满
SYS_ERR_HERO_MAIN_EVOLUTION_CNT_LIMIT = 121	-- 进化主将不可再进化
SYS_ERR_HERO_EVOLUTION_FODDER_ERROR = 122	-- 进化素材卡有误
SYS_ERR_HERO_EXP_LIMIT = 124   -- 选择武将祭司经验溢出
SYS_ERR_HERO_STAR = 125 	   -- 武将强化选择了超过4星
SYS_ERR_HERO_MAIN_HERO_ERROR = 126		-- 主将卡有误
SYS_ERR_HERO_LEVEL_NOT_ENOUGH = 127 -- 武将等级不够
SYS_ERR_HERO_BAG_BUY_LIMIT = 301	-- 购买武将背包上限

SYS_ERR_STORE_BUY_LIMIT = 140		-- 商城购买上限
SYS_LEGEND_SHOP_BUY_EXPIRE = 141	-- 传奇商店购买过期
SYS_LEGEND_SHOP_BUY_AGAIN = 142		-- 传奇商店购买过
SYS_ERR_STORE_ITEM_NOT_EXIST = 143	-- 商城道具不存在
SYS_ERR_STORE_ITEM_CLOSE = 144		-- 商城道具过期
SYS_ERR_STORE_DAILY_BUY_LIMIT = 145		-- 当天购买次数上限
SYS_ERR_STORE_TOTAL_BUY_LIMIT = 146		-- 总购买次数上限

SYS_ERR_NOT_FIRST_RECHARGE_AWARD = 150    --首充奖品不可领
SYS_ERR_HAVE_RECEIVE_FIRST_RECHARGE_AWARD = 151   --首充奖品已领
SYS_ERR_ACCUMULATED_RECHARGE_GIFT_DONT_RECV = 152 --累充未达条件
SYS_ERR_ACCUMULATED_RECHARGE_GIFT_HAS_RECV = 153 --累充已领取
SYS_ERR_ACCUMULATED_RECHARGE_OVER = 154 --累充活动已结束

SYS_ERR_STAR_SOUL_NOT_ENOUGH = 180 	-- 星魂不够

SYS_ERR_DAILY_TASK_COUNT_LACK = 190 -- 每日任务完成次数不够
SYS_ERR_DAILY_TASK_HAS_RECV = 190 -- 每日任务已经领取

SYS_ERR_SERVER_GIFT_HAS_RECV = 200  -- 开服礼包已经领取

SYS_ERR_VIP_GIFT_LEVEL_NOT_ENOUGH = 202 -- vip等级不够买vip礼包
SYS_ERR_BEAUTY_ITEM_NOT_EXIST = 203	-- 美人道具不存在
SYS_ERR_VIR_NOT_EXIST = 204         -- 参数错误

SYS_ERR_ZHAOCAI_COUNT_NOT_ENOUGH = 251	-- 招财次数不够

SYS_ERR_YZ_OPER = 300 -- 远征非法操作
SYS_ERR_YZ_HERO_LIST_NULL = 301 -- 英雄列表不能为空
SYS_ERR_YZ_HAS_DRAW = 302 -- 已经领取
SYS_ERR_YZ_LEFT_COUNT = 303 -- 剩余次数不足

SYS_ERR_CARBON_SWEEP_COUNT_NOT_ENOUGH = 553 -- 扫荡剩余次数不够

SYS_ERR_CHAT_ILL_WORD = 400 -- 含非法字符
SYS_ERR_CHAT_LVL_LIMIT = 401 -- 等级限制
SYS_ERR_CHAT_W_CNT_LIMIT = 402 -- 次数限制
SYS_ERR_CHAT_SILENT = 403 -- 已禁言
SYS_ERR_CHAT_TOO_FAST = 404 -- 喝口茶再聊

SYS_ERR_TOWER_ERR = 405 -- 爬塔开箱次数不一致
